# File Loading
file_loading_details:
  sheet_name: 'Table 1'
  skiprows: 1

expected_columns_and_types_dict:
  'Period': 'date'
  'ABN': 'str'
  'Institution Name': 'str'
  'Cash and deposits with financial institutions': 'float'
  'Trading securities': 'float'
  'Investment securities': 'float'
  'Net acceptances of customers': 'float'
  'Total residents assets': 'float'
  'Total securitised assets on balance sheet': 'float'
  'Loans to non-financial businesses': 'float'
  'Loans to financial institutions': 'float'
  'Loans to general government': 'float'
  'Loans to households: Housing: Owner-occupied': 'float'
  'Loans to households: Housing: Investment': 'float'
  'Loans to households: Credit cards': 'float'
  'Loans to households: Other': 'float'
  'Loans to community service organisations': 'float'
  'Total residents loans and finance leases': 'float'
  'Intra-group loans and finance leases': 'float'
  'Acceptances': 'float'
  'Intra-group deposits': 'float'
  'Negotiable Certificates of Deposit': 'float'
  'Total short-term borrowings': 'float'
  'Total long-term borrowings': 'float'
  'Deposits by non-financial businesses': 'float'
  'Deposits by financial institutions': 'float'
  'Deposits by general government': 'float'
  'Deposits by households': 'float'
  'Deposits by community service organisations': 'float'
  'Total residents deposits': 'float'

# 'column_type_lists' is generated in code to group the `expected_columns_and_types_dict` by type

# column settings
column_settings:
  # Grouping Columns
  company_column: 'Institution Name'
  abn_column: 'ABN'
  
  # Set default selections
  default_company: 'Macquarie Bank Limited'


# Apply column adjustments (optional)
column_adjustments_dict:
  dollars_conversion:
    all_but: ['Period', 'ABN', 'Institution Name']
    ordered_adjustments:
      multiply: 1000000

# Generate calculated columns for source data (optional)
source_data_calculated_columns:
  'Business Loans': [
    ['add', 'Loans to non-financial businesses'],
    ['add', 'Loans to financial institutions'],
  ]

# Generate calculated columns for summary data (optional)
summary_data_calculated_columns:
  'Total Loans for Housing': [
    ['add', 'Loans to households: Housing: Owner-occupied'],
    ['add', 'Loans to households: Housing: Investment'],
  ]
  'Loans to Housing: Owner-occupied Property Percentage': [
    ['add', 'Loans to households: Housing: Owner-occupied'],
    ['divide', 'Total Loans for Housing'],
  ]
  'Loans to Housing: Investment Property Percentage': [
    ['add', 'Loans to households: Housing: Investment'],
    ['divide', 'Total Loans for Housing'],
  ]

value_columns_to_graph:
  'Cash and deposits with financial institutions': '#FFFFFF'
  'Trading securities': '#FFFFFF'
  'Investment securities': '#FFFFFF'
  'Total residents assets': '#FFFFFF'
  'Total securitised assets on balance sheet': '#FFFFFF'
  'Loans to non-financial businesses': '#FFFFFF'
  'Loans to financial institutions': '#FFFFFF'
  'Loans to general government': '#FFFFFF'
  'Loans to households: Housing: Owner-occupied': '#FFFFFF'
  'Loans to households: Housing: Investment': '#FFFFFF'
  'Loans to households: Credit cards': '#FFFFFF'
  'Loans to households: Other': '#FFFFFF'
  'Loans to community service organisations': '#FFFFFF'
  'Total residents loans and finance leases': '#FFFFFF'
  'Intra-group loans and finance leases': '#FFFFFF'
  'Intra-group deposits': '#FFFFFF'
  'Negotiable Certificates of Deposit': '#FFFFFF'
  'Total short-term borrowings': '#FFFFFF'
  'Total long-term borrowings': '#FFFFFF'
  'Deposits by non-financial businesses': '#FFFFFF'
  'Deposits by financial institutions': '#FFFFFF'
  'Deposits by general government': '#FFFFFF'
  'Deposits by households': '#FFFFFF'
  'Deposits by community service organisations': '#FFFFFF'
  'Total residents deposits': '#FFFFFF'
  'Business Loans': '#FFFFFF'

# Define reference period to use in analysis
reference_dates_config:
  # Entry for 1 month ago
  1_month:
    info:
      months_int: 1
      name: "1 month"  # Name of the period
      over_period: "Over the last month"  # Description of the period
    fallback: null  # No fallback, this is the last option for 1 month

  # Entry for 6 months ago
  6_months:
    info:
      months_int: 6
      name: "6 months"
      over_period: "Over the last 6 months"
    fallback: null  # No fallback, this is the last option for 6 months

  # Entry for 12 months ago
  12_months:
    info:
      months_int: 12
      name: "1 year"
      over_period: "Over the last year"
    fallback: null  # No fallback, this is the last option for 12 months

  # Entry for 120 months ago (10 years)
  long_term:
    info:
      months_int: 120
      name: "10 years"
      over_period: "Over the past 10 years"
    fallback:
      # Fallback if 10 years ago is not available, try 5 years
      long_term:
        info:
          months_int: 60
          name: "5 years"
          over_period: "Over the past 5 years"
        fallback:
          # Fallback if 5 years ago is not available, try 4 years
          long_term:
            info:
              months_int: 40
              name: "4 years"
              over_period: "Over the past 4 years"
            fallback:
              # Fallback if 4 years ago is not available, final fallback is 3 years
              long_term:
                info:
                  months_int: 36
                  name: "3 years"
                  over_period: "Over the past 3 years"
                fallback: null  # No further fallback after 3 years